spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/cubby
spring.datasource.username=cubby
spring.datasource.password=cubbydev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true